'use client';
import {useEffect,useMemo,useState} from 'react';
import {browserSupabase} from '@/lib/supabase-browser';

type Role='owner'|'editor'|'viewer';
type Visibility='private'|'shared'|'public';
type Member={userId:string;email:string;name:string;role:Role};
type Invitation={id:string;email:string;role:'editor'|'viewer';expires_at:string;accepted_at?:string|null;created_at:string};
type AccessData={account:{id:string;email:string;name?:string}|null;role:Role|null;members:Member[];invitations:Invitation[]};

export default function AccountAccess({tripId}:{tripId:string}){
 const [data,setData]=useState<AccessData>({account:null,role:null,members:[],invitations:[]});
 const [email,setEmail]=useState('');const [inviteRole,setInviteRole]=useState<'editor'|'viewer'>('editor');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [inviteUrl,setInviteUrl]=useState('');
 const [visibility,setVisibility]=useState<Visibility>('public');const [shareUrl,setShareUrl]=useState('');
 const inviteToken=useMemo(()=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('accountInvite')??'',[tripId]);
 async function load(){try{const [membersResponse,visibilityResponse]=await Promise.all([fetch(`/api/account/members?tripId=${encodeURIComponent(tripId)}`,{cache:'no-store'}),fetch(`/api/account/visibility?tripId=${encodeURIComponent(tripId)}`,{cache:'no-store'})]);if(membersResponse.ok)setData(await membersResponse.json());if(visibilityResponse.ok){const result=await visibilityResponse.json() as {visibility?:Visibility};if(result.visibility)setVisibility(result.visibility);}}catch{}}
 useEffect(()=>{void load();},[tripId]);
 useEffect(()=>{if(!inviteToken||!data.account)return;void (async()=>{setBusy(true);const response=await fetch('/api/account/accept',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tripId,token:inviteToken})});const result=await response.json();setBusy(false);if(response.ok){setMessage('Invitation accepted. Your trip access is active.');const url=new URL(window.location.href);url.searchParams.delete('accountInvite');history.replaceState({},'',url);await load();window.setTimeout(()=>window.location.reload(),400);}else setMessage(result.error??'Could not accept this invitation.');})();},[inviteToken,data.account?.id,tripId]);
 async function emailSignIn(){setBusy(true);setMessage('');const {error}=await browserSupabase.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:window.location.href,shouldCreateUser:true}});setBusy(false);setMessage(error?.message??'Check your email for a secure Trip Hub sign-in link.');}
 async function googleSignIn(){setBusy(true);setMessage('');const {error}=await browserSupabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.href}});if(error){setBusy(false);setMessage(error.message);}}
 async function signOut(){setBusy(true);await browserSupabase.auth.signOut();await fetch('/api/account/session',{method:'DELETE'});window.location.reload();}
 async function claim(){setBusy(true);const response=await fetch('/api/account/members',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tripId,action:'claim_owner'})});const result=await response.json();setBusy(false);setMessage(response.ok?'This trip is now attached to your account.':result.error??'Could not claim this trip.');if(response.ok){await load();window.setTimeout(()=>window.location.reload(),300);}}
 async function invite(){setBusy(true);setInviteUrl('');const response=await fetch('/api/account/invite',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tripId,email,role:inviteRole})});const result=await response.json();setBusy(false);if(response.ok){setInviteUrl(result.url);setMessage(`Invite ready for ${result.email}.`);setEmail('');await load();}else setMessage(result.error??'Could not create invitation.');}
 async function copyInvite(){if(inviteUrl){await navigator.clipboard.writeText(inviteUrl);setMessage('Invite link copied.');}}
 async function setRole(member:Member,role:Role){setBusy(true);const response=await fetch('/api/account/members',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tripId,action:'set_role',userId:member.userId,role})});const result=await response.json();setBusy(false);if(!response.ok)setMessage(result.error??'Could not update access.');else await load();}
 async function remove(member:Member){if(!window.confirm(`Remove ${member.email||member.name} from this trip?`))return;setBusy(true);const response=await fetch(`/api/account/members?tripId=${encodeURIComponent(tripId)}&userId=${encodeURIComponent(member.userId)}`,{method:'DELETE'});const result=await response.json();setBusy(false);if(!response.ok)setMessage(result.error??'Could not remove member.');else await load();}
 async function changeVisibility(next:Visibility){setBusy(true);setMessage('');try{const response=await fetch('/api/account/visibility',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tripId,visibility:next})});const result=await response.json() as {visibility?:Visibility;shareUrl?:string;error?:string};if(!response.ok)throw new Error(result.error??'Could not update trip visibility.');setVisibility(result.visibility??next);setShareUrl(result.shareUrl??'');setMessage(next==='private'?'Trip is private. Only named members can open it.':next==='shared'?'Trip is shared by link. Anyone with the special link can view it.':'Trip is public. Anyone with the trip URL can view it.');}catch(error){setMessage(error instanceof Error?error.message:'Could not update trip visibility.');}finally{setBusy(false);}}
 async function copyShare(){let url=shareUrl;if(!url){const response=await fetch('/api/account/visibility',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tripId,visibility:'shared'})});const result=await response.json() as {shareUrl?:string;error?:string};if(!response.ok||!result.shareUrl){setMessage(result.error??'Could not create shared link.');return;}url=result.shareUrl;setShareUrl(url);setVisibility('shared');}await navigator.clipboard.writeText(url);setMessage('Shared viewing link copied.');}
 return <section className="accountAccess"><div className="between"><div><div className="eyebrow">TRIP ACCOUNTS</div><h3>Named access</h3><p className="muted small">Use an account for persistent access across devices. The shared PIN remains available as an owner fallback during the transition.</p></div>{data.account&&<button className="textButton" disabled={busy} onClick={()=>void signOut()}>Sign out</button>}</div>
  {!data.account?<div className="accountSignIn"><div className="accountEmail"><input className="field" type="email" placeholder="you@example.com" value={email} onChange={event=>setEmail(event.target.value)}/><button className="btn primary" disabled={busy||!email.trim()} onClick={()=>void emailSignIn()}>Email me a sign-in link</button></div><button className="btn" disabled={busy} onClick={()=>void googleSignIn()}>Continue with Google</button>{inviteToken&&<p className="accountInviteNotice">Sign in with the email that received this trip invitation to accept it.</p>}</div>:<><div className="accountIdentity"><span className="accountAvatar">{(data.account.name||data.account.email).slice(0,1).toUpperCase()}</span><div><strong>{data.account.name||data.account.email}</strong><small>{data.account.email}{data.role?` · ${data.role}`:' · no named role on this trip yet'}</small></div></div>{!data.role&&<div className="accountClaim"><p>This trip is not attached to your account yet. If you are the owner, unlock editing with the owner PIN first, then claim it.</p><button className="btn primary" disabled={busy} onClick={()=>void claim()}>Claim trip ownership</button></div>}
   {data.role==='owner'&&<><div className="accountVisibility"><div><strong>Who can view this trip?</strong><p className="muted small">Named members always keep access. This setting controls everyone else.</p></div><div className="visibilityChoices"><button className={`visibilityChoice ${visibility==='private'?'selected':''}`} disabled={busy} onClick={()=>void changeVisibility('private')}><strong>Private</strong><small>Only owners, editors, and viewers you invite.</small></button><button className={`visibilityChoice ${visibility==='shared'?'selected':''}`} disabled={busy} onClick={()=>void changeVisibility('shared')}><strong>Shared by link</strong><small>Anyone with a special viewing link can open it.</small></button><button className={`visibilityChoice ${visibility==='public'?'selected':''}`} disabled={busy} onClick={()=>void changeVisibility('public')}><strong>Public</strong><small>Anyone with the normal trip URL can view it.</small></button></div>{visibility==='shared'&&<button className="btn" disabled={busy} onClick={()=>void copyShare()}>Copy shared viewing link</button>}</div><div className="accountInviteForm"><div><strong>Invite a traveler</strong><p className="muted small">They will sign in with their own account; no shared editor PIN is needed.</p></div><div className="accountInviteFields"><input className="field" type="email" placeholder="traveler@example.com" value={email} onChange={event=>setEmail(event.target.value)}/><select className="field" value={inviteRole} onChange={event=>setInviteRole(event.target.value as 'editor'|'viewer')}><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button className="btn primary" disabled={busy||!email.trim()} onClick={()=>void invite()}>Create invite</button></div>{inviteUrl&&<div className="accountInviteLink"><span>{inviteUrl}</span><button className="btn" onClick={()=>void copyInvite()}>Copy</button></div>}</div><div className="accountMembers"><strong>People on this trip</strong>{data.members.map(member=><div className="accountMember" key={member.userId}><div><span>{member.name||member.email||'Trip member'}</span><small>{member.email}</small></div><div>{member.userId===data.account?.id?<span className="chip">{member.role}</span>:<><select className="field" value={member.role} disabled={busy} onChange={event=>void setRole(member,event.target.value as Role)}><option value="owner">Owner</option><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button className="textButton dangerText" disabled={busy} onClick={()=>void remove(member)}>Remove</button></>}</div></div>)}{data.invitations.filter(item=>!item.accepted_at).map(item=><div className="accountMember pending" key={item.id}><div><span>{item.email}</span><small>Invite pending · expires {new Date(item.expires_at).toLocaleDateString()}</small></div><span className="chip neutral">{item.role}</span></div>)}</div></>}
  </>}{message&&<p className="accountMessage" role="status">{message}</p>}</section>;
}
