'use client';
import {useState} from 'react';
import {browserSupabase} from '@/lib/supabase-browser';

type LegacyTrip={id:string;title:string;destinations:string};
export default function MyTripsAccount({account,legacyTrips=[]}:{account:{email:string;name?:string}|null;legacyTrips?:LegacyTrip[]}){
 const [email,setEmail]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [claimed,setClaimed]=useState<string[]>([]);
 const remaining=legacyTrips.filter(trip=>!claimed.includes(trip.id));
 async function emailSignIn(){setBusy(true);setMessage('');const {error}=await browserSupabase.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:window.location.href,shouldCreateUser:true}});setBusy(false);setMessage(error?.message??'Check your email for a secure Trip Hub sign-in link.');}
 async function googleSignIn(){setBusy(true);setMessage('');const {error}=await browserSupabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.href}});if(error){setBusy(false);setMessage(error.message);}}
 async function signOut(){setBusy(true);await browserSupabase.auth.signOut();await fetch('/api/account/session',{method:'DELETE'});window.location.reload();}
 async function claimTrip(trip:LegacyTrip){setBusy(true);setMessage('');try{const response=await fetch('/api/account/members',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tripId:trip.id,action:'claim_owner'})});const result=await response.json();if(!response.ok)throw new Error(result.error??'Could not attach this trip.');setClaimed(current=>[...current,trip.id]);setMessage(`${trip.title} is now attached to your account.`);window.setTimeout(()=>window.location.reload(),500);}catch(error){setMessage(error instanceof Error?error.message:'Could not attach this trip.');}finally{setBusy(false);}}
 async function claimAll(){setBusy(true);setMessage('');let count=0;try{for(const trip of remaining){const response=await fetch('/api/account/members',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tripId:trip.id,action:'claim_owner'})});if(response.ok){count++;setClaimed(current=>[...current,trip.id]);}}setMessage(`${count} older trip${count===1?'':'s'} attached to your account.`);if(count)window.setTimeout(()=>window.location.reload(),600);}finally{setBusy(false);}}
 if(account)return <><div className="myTripsAccount signedIn"><div><span className="accountAvatar">{(account.name||account.email).slice(0,1).toUpperCase()}</span><div><strong>{account.name||account.email}</strong><small>{account.email} · Trip Hub account</small></div></div><button className="textButton" disabled={busy} onClick={()=>void signOut()}>Sign out</button></div>{remaining.length>0&&<section className="card accountMigration"><div className="between"><div><div className="eyebrow">ONE-TIME ACCOUNT MIGRATION</div><h2>Bring your older trips into this account</h2><p className="muted">These trips were created before named accounts. Attach them once and they will appear normally on every device where you sign in.</p></div><span className="chip">{remaining.length} found</span></div><div className="migrationTrips">{remaining.map(trip=><article key={trip.id}><div><strong>{trip.title}</strong><small>{trip.destinations}</small></div><button className="btn" disabled={busy} onClick={()=>void claimTrip(trip)}>Attach to my account</button></article>)}</div>{remaining.length>1&&<button className="btn primary" disabled={busy} onClick={()=>void claimAll()}>Attach all {remaining.length} trips</button>}<p className="muted small">This migration option disappears automatically when there are no older trips left to attach.</p>{message&&<p className="accountMessage" role="status">{message}</p>}</section>}</>;
 return <section className="card myTripsSignIn"><div><div className="eyebrow">YOUR TRIPS</div><h2>Sign in to see your trips</h2><p className="muted">Your trip list is private. Public trip links still open directly when someone has the shared URL.</p></div><div className="myTripsSignInActions"><div className="accountEmail"><input className="field" type="email" placeholder="you@example.com" value={email} onChange={event=>setEmail(event.target.value)}/><button className="btn primary" disabled={busy||!email.trim()} onClick={()=>void emailSignIn()}>Email me a sign-in link</button></div><button className="btn" disabled={busy} onClick={()=>void googleSignIn()}>Continue with Google</button></div>{message&&<p className="accountMessage" role="status">{message}</p>}</section>;
}
