'use client';
import {useEffect,useMemo,useState} from 'react';
import type {TripState} from '@/lib/types';
const tabs=['Today','Itinerary','Food','Places','Checklist'] as const;type Tab=typeof tabs[number];
export default function TripApp(){const [state,setState]=useState<TripState|null>(null);const [tab,setTab]=useState<Tab>('Today');const [cloud,setCloud]=useState(false);const [query,setQuery]=useState('');
useEffect(()=>{fetch('/api/state').then(r=>r.json()).then(x=>{const local=localStorage.getItem('trip-state');setState(x.cloud?x.state:(local?JSON.parse(local):x.state));setCloud(x.cloud)})},[]);
async function persist(next:TripState){setState(next);localStorage.setItem('trip-state',JSON.stringify(next));if(cloud)await fetch('/api/state',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(next)})}
function toggleDay(di:number,ii:number){if(!state)return;const n=structuredClone(state);n.days[di].items[ii].done=!n.days[di].items[ii].done;persist(n)}
function toggleList(key:'foods'|'packing',i:number){if(!state)return;const n=structuredClone(state);n[key][i].done=!n[key][i].done;persist(n)}
const today=useMemo(()=>state?.days[0],[state]);if(!state)return <main className="shell"><div className="card">Loading trip…</div></main>;
const filtered=state.places.filter(p=>`${p.name} ${p.notes} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
return <><main className="shell"><div className="top"><div><div className="title">Toronto • Niagara • Buffalo</div><div className="sub">Sept. 24–Oct. 1, 2026 · {cloud?'Shared cloud sync':'This-device mode'}</div></div><button className="btn" onClick={()=>fetch('/api/auth',{method:'DELETE'}).then(()=>location.reload())}>Lock</button></div><nav className="tabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
{tab==='Today'&&today&&<section><div className="card"><div className="between"><h2>{today.label}: {today.city}</h2><span className="chip">{today.items.filter(i=>i.done).length}/{today.items.length}</span></div></div>{today.items.map((x,i)=><label className={`card row ${x.done?'done':''}`} key={x.id}><input type="checkbox" checked={x.done} onChange={()=>toggleDay(0,i)}/><div><h3>{x.time} · {x.title}</h3>{x.details&&<div className="muted">{x.details}</div>}</div></label>)}</section>}
{tab==='Itinerary'&&<section>{state.days.map((d,di)=><div className="card" key={d.date}><div className="between"><h2>{d.label} · {d.city}</h2><span className="chip">{d.items.filter(i=>i.done).length}/{d.items.length}</span></div>{d.items.map((x,ii)=><label className={`row ${x.done?'done':''}`} style={{padding:'9px 0',borderTop:'1px solid var(--line)'}} key={x.id}><input type="checkbox" checked={x.done} onChange={()=>toggleDay(di,ii)}/><div><strong>{x.time} — {x.title}</strong>{x.optional&&<span className="chip">optional</span>}{x.details&&<div className="muted small">{x.details}</div>}</div></label>)}</div>)}</section>}
{tab==='Food'&&<section>{['Try','Bring home'].map(cat=><div key={cat}><h2>{cat}</h2><div className="grid">{state.foods.map((f,i)=>f.category===cat&&<label className={`card row ${f.done?'done':''}`} key={f.id}><input type="checkbox" checked={f.done} onChange={()=>toggleList('foods',i)}/><div><h3>{f.title}</h3>{f.notes&&<div className="muted small">{f.notes}</div>}</div></label>)}</div></div>)}</section>}
{tab==='Places'&&<section><input className="field" placeholder="Search saved places…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="muted small">{filtered.length} saved places</p><div className="grid">{filtered.map(p=><article className="card" key={p.id}><div className="between"><h3>{p.name}</h3><span className="chip">{p.category}</span></div><div className="muted small">{p.region}</div>{p.notes&&<p>{p.notes}</p>}<a className="btn primary" href={p.mapUrl} target="_blank">Open Map</a></article>)}</div></section>}
{tab==='Checklist'&&<section>{[...new Set(state.packing.map(x=>x.category))].map(cat=><div key={cat}><h2>{cat}</h2><div className="grid">{state.packing.map((p,i)=>p.category===cat&&<label className={`card row ${p.done?'done':''}`} key={p.id}><input type="checkbox" checked={p.done} onChange={()=>toggleList('packing',i)}/><div>{p.title}</div></label>)}</div></div>)}</section>}</main></>}
