'use client';

import {useState} from 'react';
import {useRouter} from 'next/navigation';
import type {TripSummary} from '@/lib/trips';

export default function TripManager({trip,canOwn=true}:{trip:TripSummary;canOwn?:boolean}){
 const router=useRouter();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [title,setTitle]=useState(trip.title);const [destinations,setDestinations]=useState(trip.destinations);const [startDate,setStartDate]=useState(trip.startDate);const [endDate,setEndDate]=useState(trip.endDate);
 async function request(method:string,body?:unknown){const response=await fetch(`/api/trips/${encodeURIComponent(trip.id)}`,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error??'Trip update failed.');return result;}
 async function save(){setBusy(true);setError('');try{await request('PATCH',{title,destinations,startDate,endDate});setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Trip update failed.');}finally{setBusy(false);}}
 async function archive(){setBusy(true);setError('');try{await request('PATCH',{archived:trip.status!=='archived'});setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Trip update failed.');}finally{setBusy(false);}}
 async function duplicate(){setBusy(true);setError('');try{const result=await request('POST',{action:'duplicate',title:`${trip.title} copy`,startDate,endDate});router.push(`/trips/${result.tripId}`);}catch(e){setError(e instanceof Error?e.message:'Trip could not be duplicated.');setBusy(false);}}
 async function remove(){if(!window.confirm(`Delete “${trip.title}” permanently? This cannot be undone.`))return;setBusy(true);setError('');try{await request('DELETE');setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Trip could not be deleted.');setBusy(false);}}
 return <div className="tripManage"><button className="tripManageButton" aria-label={`Manage ${trip.title}`} onClick={event=>{event.preventDefault();event.stopPropagation();setOpen(true);}}>•••</button>{open&&<div className="editorUnlockBackdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)setOpen(false);}}><section className="card tripManageDialog" role="dialog" aria-modal="true"><button className="editorUnlockClose" onClick={()=>setOpen(false)} disabled={busy}>×</button><div className="eyebrow">TRIP MANAGEMENT</div><h2>{trip.title}</h2><div className="tripManageFields"><label>Trip title<input className="field" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Destination(s)<input className="field" value={destinations} onChange={e=>setDestinations(e.target.value)}/></label><div className="createTripDates"><label>Start date<input className="field" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>End date<input className="field" type="date" min={startDate||undefined} value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div><p className="muted small">Changing dates keeps your itinerary in the same day order and shifts it onto the new trip dates.</p></div>{error&&<p className="error">{error}</p>}<div className="tripManagePrimary"><button className="btn primary" onClick={save} disabled={busy||!title.trim()||!destinations.trim()||!startDate||!endDate}>{busy?'Working…':'Save trip details'}</button><button className="btn" onClick={duplicate} disabled={busy}>Duplicate / start from this trip</button></div>{canOwn&&<div className="tripManageDanger"><button className="textButton" onClick={archive} disabled={busy}>{trip.status==='archived'?'Restore from archive':'Archive trip'}</button><button className="textButton dangerText" onClick={remove} disabled={busy}>Delete permanently</button></div>}</section></div>}</div>;
}
